version: "3.7"

services:
  app:
    restart: on-failure
    build:
      context: .
    # expose:
    #   - "8000"
    ports:
      - 8000:8000
      - 5000:5000
    volumes:
      - app-data:/usr/src/app/static
      - .:/usr/src/app/
    env_file:
      - .env
    networks:
      - dev
    command: gunicorn --bind 0.0.0.0:5000 manage:app

  # nginx:
  #   restart: unless-stopped
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - .:/www/static
  #     - web-data:/usr/src/app/static
  #   networks:
  #     - dev
  neo4j:
    image: neo4j:4.0.3
    restart: unless-stopped
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
    env_file:
      - .env.dev
    networks:
      - dev

  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  app-data:
  neo4j-data:
  postgres_data:
